object FrmCadastroUsuario: TFrmCadastroUsuario
  Left = 0
  Top = 0
  Caption = 'Cadastro Usuario'
  ClientHeight = 344
  ClientWidth = 493
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poMainFormCenter
  OnShow = FormShow
  TextHeight = 15
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 493
    Height = 107
    Align = alTop
    Color = 8947848
    ParentBackground = False
    TabOrder = 0
    object PnNovo: TPanel
      Left = 0
      Top = -1
      Width = 80
      Height = 52
      Caption = 'Novo'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      OnClick = PnNovoClick
      OnMouseEnter = PnNovoMouseEnter
      OnMouseLeave = PnNovoMouseLeave
    end
    object PnEditar: TPanel
      Left = 79
      Top = -1
      Width = 80
      Height = 52
      Caption = 'Editar'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
      OnClick = PnEditarClick
      OnMouseEnter = PnEditarMouseEnter
      OnMouseLeave = PnEditarMouseLeave
    end
    object PnCancelar: TPanel
      Left = 154
      Top = -1
      Width = 80
      Height = 52
      Caption = 'Cancelar'
      Color = 6710886
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 3355443
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 2
      OnClick = PnCancelarClick
      OnMouseEnter = PnCancelarMouseEnter
      OnMouseLeave = PnCancelarMouseLeave
    end
    object PnExcluir: TPanel
      Left = 232
      Top = -1
      Width = 80
      Height = 52
      Caption = 'Excluir'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 3
      OnClick = PnExcluirClick
      OnMouseEnter = PnExcluirMouseEnter
      OnMouseLeave = PnExcluirMouseLeave
    end
    object PnGravar: TPanel
      Left = 304
      Top = -1
      Width = 80
      Height = 52
      Caption = 'Gravar'
      Color = 6710886
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 3355443
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 4
      OnClick = PnGravarClick
      OnMouseEnter = PnGravarMouseEnter
      OnMouseLeave = PnGravarMouseLeave
    end
    object PnSair: TPanel
      Left = 413
      Top = 0
      Width = 80
      Height = 59
      Caption = 'Sair'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 5
      OnClick = PnSairClick
      OnMouseEnter = PnSairMouseEnter
      OnMouseLeave = PnSairMouseLeave
    end
    object PnUltimo: TPanel
      Left = 412
      Top = 57
      Width = 80
      Height = 52
      Caption = #218'ltimo'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 6
      OnClick = PnUltimoClick
      OnMouseEnter = PnUltimoMouseEnter
      OnMouseLeave = PnUltimoMouseLeave
    end
    object PnProximo: TPanel
      Left = 336
      Top = 57
      Width = 80
      Height = 52
      Caption = 'Proximo'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 7
      OnClick = PnProximoClick
      OnMouseEnter = PnProximoMouseEnter
      OnMouseLeave = PnProximoMouseLeave
    end
    object PnAnterior: TPanel
      Left = 257
      Top = 57
      Width = 80
      Height = 52
      Caption = 'Anterior'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 8
      OnClick = PnAnteriorClick
      OnMouseEnter = PnAnteriorMouseEnter
      OnMouseLeave = PnAnteriorMouseLeave
    end
    object PnPrimeiro: TPanel
      Left = 179
      Top = 57
      Width = 80
      Height = 52
      Caption = 'Primeiro'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 9
      OnClick = PnPrimeiroClick
      OnMouseEnter = PnPrimeiroMouseEnter
      OnMouseLeave = PnPrimeiroMouseLeave
    end
    object PnLocaliza: TPanel
      Left = 102
      Top = 57
      Width = 80
      Height = 52
      Caption = 'Localiza'
      Color = 6710886
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 10
      OnMouseEnter = PnLocalizaMouseEnter
      OnMouseLeave = PnLocalizaMouseLeave
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 107
    Width = 493
    Height = 237
    Align = alClient
    Color = 8947848
    ParentBackground = False
    TabOrder = 1
    object lbEndereco: TLabel
      Left = 24
      Top = 127
      Width = 38
      Height = 14
      Caption = 'Senha'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object LbNomeCli: TLabel
      Left = 24
      Top = 67
      Width = 34
      Height = 14
      Caption = 'Nome'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label2: TLabel
      Left = 304
      Top = 88
      Width = 32
      Height = 15
      Caption = 'Senha'
    end
    object Label1: TLabel
      Left = 23
      Top = 20
      Width = 13
      Height = 14
      Caption = 'Id'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object edtNomeUsuario: TDBEdit
      Left = 23
      Top = 87
      Width = 326
      Height = 23
      DataField = 'Usuario'
      DataSource = dmConexoes.dsUsuario
      Enabled = False
      TabOrder = 0
    end
    object edtSenha: TDBEdit
      Left = 25
      Top = 147
      Width = 326
      Height = 23
      DataField = 'Senha'
      DataSource = dmConexoes.dsUsuario
      Enabled = False
      TabOrder = 1
    end
    object edtID: TDBEdit
      Left = 24
      Top = 40
      Width = 34
      Height = 23
      DataField = 'ID'
      DataSource = dmConexoes.dsUsuario
      Enabled = False
      TabOrder = 2
    end
  end
end
